#!/usr/bin/env node
/**
 * scaffold-workers.mjs
 * Creates 95 worker agent .md files under agents/workers/
 */
import { writeFileSync, mkdirSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");
const outDir = join(root, "agents", "workers");
mkdirSync(outDir, { recursive: true });

// Each entry: { domain, name, title, isolation, capability, director, input, output, role, artifactDesc, validators }
const workers = [
  // ── Section Build (5) ──────────────────────────────────────────────────────
  { domain: "section-build", name: "nextjs-section", title: "Next.js Section Builder", isolation: "worktree", capability: "build-nextjs-section", director: "wave-director", input: "SectionSpec", output: "SectionArtifact", role: "Builds a single page section as a Next.js RSC with Tailwind v4 DNA tokens, animation, and 4-breakpoint responsive layout.", artifactDesc: "section/ directory with page.tsx, component files, and SUMMARY.md", validators: "quality-gate-v3, archetype-specificity" },
  { domain: "section-build", name: "astro-section", title: "Astro Section Builder", isolation: "worktree", capability: "build-astro-section", director: "wave-director", input: "SectionSpec", output: "SectionArtifact", role: "Builds a single page section as an Astro component with DNA tokens, island hydration strategy, and 4-breakpoint layout.", artifactDesc: "section/ directory with .astro component files and SUMMARY.md", validators: "quality-gate-v3, archetype-specificity" },
  { domain: "section-build", name: "sveltekit-section", title: "SvelteKit Section Builder", isolation: "worktree", capability: "build-sveltekit-section", director: "wave-director", input: "SectionSpec", output: "SectionArtifact", role: "Builds a single page section as a SvelteKit component with DNA tokens, Svelte transitions, and 4-breakpoint responsive layout.", artifactDesc: "section/ directory with .svelte files and SUMMARY.md", validators: "quality-gate-v3, archetype-specificity" },
  { domain: "section-build", name: "vue-section", title: "Vue Section Builder", isolation: "worktree", capability: "build-vue-section", director: "wave-director", input: "SectionSpec", output: "SectionArtifact", role: "Builds a single page section as a Vue 3 SFC with DNA tokens, GSAP/VueUse motion, and 4-breakpoint responsive layout.", artifactDesc: "section/ directory with .vue SFC files and SUMMARY.md", validators: "quality-gate-v3, archetype-specificity" },
  { domain: "section-build", name: "react-vite-section", title: "React/Vite Section Builder", isolation: "worktree", capability: "build-react-vite-section", director: "wave-director", input: "SectionSpec", output: "SectionArtifact", role: "Builds a single page section as a React component with Vite, DNA tokens, Framer Motion, and 4-breakpoint responsive layout.", artifactDesc: "section/ directory with .tsx component files and SUMMARY.md", validators: "quality-gate-v3, archetype-specificity" },

  // ── 3D (8) ─────────────────────────────────────────────────────────────────
  { domain: "3d", name: "hero-camera-choreographer", title: "Hero Camera Choreographer", isolation: "in-process", capability: "choreograph-camera", director: "scene-director", input: "SceneSpec", output: "CameraTimeline", role: "Authors camera keyframe sequences for hero and cinematic sections. Produces Theatre.js or GSAP ScrollTrigger camera paths tied to DNA motion tokens.", artifactDesc: "CameraTimeline JSON with keyframes, easing curves, and scroll trigger points", validators: "motion-health, performance-animation" },
  { domain: "3d", name: "morph-target-author", title: "Morph Target Author", isolation: "in-process", capability: "author-morph-targets", director: "scene-director", input: "MeshSpec", output: "MorphTargetGLTF", role: "Generates morph target animations for character and product 3D models. Validates blend shape count against performance budget.", artifactDesc: "GLTF file with embedded morph targets and animation clips", validators: "gltf-optimization, perf-budgets" },
  { domain: "3d", name: "webgpu-shader-author", title: "WebGPU Shader Author", isolation: "in-process", capability: "author-webgpu-shader", director: "scene-director", input: "ShaderSpec", output: "WGSLShader", role: "Authors WGSL compute and fragment shaders for WebGPU-capable browsers. Provides WebGL2 fallback strategy via scene-director.", artifactDesc: "WGSL shader files with fallback metadata and DNA color injection points", validators: "cross-browser-rendering, three-d-webgl-effects" },
  { domain: "3d", name: "webgl2-fallback-author", title: "WebGL2 Fallback Author", isolation: "in-process", capability: "author-webgl2-fallback", director: "scene-director", input: "WebGPUShader", output: "GLSL300Shader", role: "Transpiles or authors equivalent GLSL 3.0 fallback shaders for WebGPU scenes. Ensures tier-1 browser compatibility.", artifactDesc: "GLSL 3.0 shader files compatible with WebGL2 context", validators: "cross-browser-rendering" },
  { domain: "3d", name: "r3f-scene-builder", title: "R3F Scene Builder", isolation: "worktree", capability: "build-r3f-scene", director: "scene-director", input: "SceneSpec", output: "R3FComponent", role: "Builds React Three Fiber scene components with Rapier physics, DNA-bound materials, and postprocessing pipeline.", artifactDesc: "R3F scene component with physics config, material bindings, and postprocessing", validators: "r3f-physics-rapier, performance-animation" },
  { domain: "3d", name: "gltf-lod-generator", title: "GLTF LOD Generator", isolation: "in-process", capability: "generate-gltf-lod", director: "scene-director", input: "GLTFAsset", output: "LODManifest", role: "Generates multiple LOD variants for GLTF models. Validates triangle counts and texture sizes against perf budgets.", artifactDesc: "LOD manifest with asset paths per quality tier and load thresholds", validators: "gltf-optimization, perf-budgets" },
  { domain: "3d", name: "ktx2-encoder", title: "KTX2 Encoder", isolation: "in-process", capability: "encode-ktx2", director: "scene-director", input: "TextureAsset", output: "KTX2Texture", role: "Encodes textures to KTX2/Basis format for GPU-compressed delivery. Validates format support matrix.", artifactDesc: "KTX2 texture files with UASTC/ETC1S variants and transcoder hints", validators: "gltf-optimization" },
  { domain: "3d", name: "spline-embed-author", title: "Spline Embed Author", isolation: "worktree", capability: "author-spline-embed", director: "scene-director", input: "SplineSpec", output: "SplineEmbedComponent", role: "Authors Spline scene embed components with lazy loading, DNA color injection via Spline events API, and reduced-motion fallback.", artifactDesc: "Spline embed component with DNA event bindings and fallback image", validators: "performance-animation, reduced-motion-variant-author" },

  // ── Motion (6) ─────────────────────────────────────────────────────────────
  { domain: "motion", name: "gsap-choreographer", title: "GSAP Choreographer", isolation: "in-process", capability: "choreograph-gsap", director: "wave-director", input: "MotionSpec", output: "GSAPTimeline", role: "Authors GSAP ScrollTrigger and timeline sequences bound to DNA motion tokens. Enforces reduced-motion variants and performance budgets.", artifactDesc: "GSAP timeline code with ScrollTrigger config and DNA token bindings", validators: "motion-health, performance-animation" },
  { domain: "motion", name: "scroll-driven-css-author", title: "Scroll-Driven CSS Author", isolation: "in-process", capability: "author-scroll-driven-css", director: "wave-director", input: "MotionSpec", output: "ScrollDrivenCSS", role: "Authors native CSS scroll-driven animations using @keyframes with animation-timeline. Provides JS-based fallback for unsupported browsers.", artifactDesc: "CSS file with scroll-driven animation declarations and feature detection fallback", validators: "cross-browser-rendering, motion-health" },
  { domain: "motion", name: "theatre-sequencer", title: "Theatre.js Sequencer", isolation: "in-process", capability: "sequence-theatre", director: "wave-director", input: "SequenceSpec", output: "TheatreProject", role: "Authors Theatre.js project files for complex multi-object animation sequences. Binds sequence values to DNA motion tokens.", artifactDesc: "Theatre.js project JSON with object sheets, sequences, and DNA token bindings", validators: "motion-health, interaction-fidelity-gate" },
  { domain: "motion", name: "lottie-author", title: "Lottie Author", isolation: "in-process", capability: "author-lottie", director: "wave-director", input: "LottieSpec", output: "LottieAnimation", role: "Authors Lottie animation JSON for micro-animations and brand motion sigils. Validates file size and frame rate targets.", artifactDesc: "Lottie JSON animation with DNA color layer mappings", validators: "brand-motion-sigils, performance-animation" },
  { domain: "motion", name: "rive-author", title: "Rive Author", isolation: "in-process", capability: "author-rive", director: "wave-director", input: "RiveSpec", output: "RiveStateMachine", role: "Authors Rive state machine definitions for interactive brand animations. Wires inputs to user interaction events.", artifactDesc: "Rive file spec with state machine inputs, transitions, and DNA color overrides", validators: "brand-motion-sigils, interaction-fidelity-gate" },
  { domain: "motion", name: "reduced-motion-variant-author", title: "Reduced Motion Variant Author", isolation: "in-process", capability: "author-reduced-motion", director: "wave-director", input: "MotionArtifact", output: "ReducedMotionVariant", role: "Generates prefers-reduced-motion CSS/JS variants for every animated section. Ensures WCAG 2.1 compliance without sacrificing design intent.", artifactDesc: "Reduced-motion CSS/JS variant with equivalent static presentation", validators: "accessibility, motion-health" },

  // ── Asset (9) ──────────────────────────────────────────────────────────────
  { domain: "asset", name: "flux-hero-gen", title: "Flux Hero Generator", isolation: "in-process", capability: "generate-flux-hero", director: "asset-director", input: "HeroAssetSpec", output: "HeroImageAsset", role: "Generates hero background images using Flux API with DNA-matched color palettes and beat-type visual language.", artifactDesc: "Hero image file with generation params and DNA color validation report", validators: "pixel-dna-extraction, asset-provenance" },
  { domain: "asset", name: "nano-banana-iterator", title: "Nano-Banana Iterator", isolation: "in-process", capability: "iterate-nano-banana", director: "asset-director", input: "ImageIterSpec", output: "IteratedImageAsset", role: "Runs iterative image editing via nano-banana MCP. Applies DNA color corrections, style transfers, and beat-specific atmosphere adjustments.", artifactDesc: "Iterated image asset with edit chain log and final DNA alignment score", validators: "pixel-dna-extraction, lpips-similarity" },
  { domain: "asset", name: "rodin-3d-gen", title: "Rodin 3D Generator", isolation: "in-process", capability: "generate-rodin-3d", director: "asset-director", input: "Model3DSpec", output: "Model3DAsset", role: "Generates 3D model assets via Rodin API. Produces GLTF output ready for scene-director pipeline.", artifactDesc: "GLTF model with material setup, provenance record, and DNA color bindings", validators: "gltf-optimization, asset-provenance" },
  { domain: "asset", name: "meshy-prototyper", title: "Meshy Prototyper", isolation: "in-process", capability: "prototype-meshy", director: "asset-director", input: "MeshySpec", output: "MeshyModel", role: "Rapid 3D prototype generation via Meshy API. Produces low-fidelity models for layout and proportion validation.", artifactDesc: "Low-fidelity GLTF prototype with topology notes and refinement flags", validators: "gltf-optimization" },
  { domain: "asset", name: "character-poser", title: "Character Poser", isolation: "in-process", capability: "pose-character", director: "asset-director", input: "PoseSpec", output: "PosedCharacter", role: "Applies poses and expressions to character models. Validates against brand character consistency guidelines.", artifactDesc: "Posed character GLTF with blend shape values and expression metadata", validators: "character-consistency, asset-provenance" },
  { domain: "asset", name: "inpainter", title: "Inpainter", isolation: "in-process", capability: "inpaint-image", director: "asset-director", input: "InpaintSpec", output: "InpaintedAsset", role: "Runs inpainting workflows to fix, extend, or composite image assets. Preserves DNA color accuracy in edited regions.", artifactDesc: "Inpainted image with edit mask, original backup, and color validation report", validators: "pixel-dna-extraction, inpainting-workflow" },
  { domain: "asset", name: "upscaler", title: "Upscaler", isolation: "in-process", capability: "upscale-asset", director: "asset-director", input: "LowResAsset", output: "UpscaledAsset", role: "Upscales raster assets to target resolution using AI super-resolution. Validates output sharpness and artifact levels.", artifactDesc: "Upscaled image at target resolution with quality metrics", validators: "upscaling, lpips-similarity" },
  { domain: "asset", name: "recraft-vector-author", title: "Recraft Vector Author", isolation: "in-process", capability: "author-recraft-vector", director: "asset-director", input: "VectorSpec", output: "SVGAsset", role: "Generates SVG vector assets via Recraft API. Binds vector colors to DNA tokens for runtime theming.", artifactDesc: "SVG file with DNA token variable bindings and viewBox optimizations", validators: "recraft-vector-ai, asset-provenance" },
  { domain: "asset", name: "video-reel-gen", title: "Video Reel Generator", isolation: "in-process", capability: "generate-video-reel", director: "asset-director", input: "VideoSpec", output: "VideoReelAsset", role: "Generates DNA-parameterized video reel assets via Remotion or video gen APIs. Outputs AVIF/MP4/WebM.", artifactDesc: "Video reel files with DNA color params, codec variants, and performance budget check", validators: "remotion-video, performance-patterns" },

  // ── Content (5) ────────────────────────────────────────────────────────────
  { domain: "content", name: "microcopy-author", title: "Microcopy Author", isolation: "in-process", capability: "author-microcopy", director: "creative-director", input: "CopySpec", output: "MicrocopyDraft", role: "Authors UI microcopy, CTA text, tooltips, and error messages aligned with brand voice and anti-slop gate.", artifactDesc: "CONTENT.md additions with microcopy variants and brand voice validation", validators: "anti-slop-gate, copy-intelligence" },
  { domain: "content", name: "brand-voice-enforcer", title: "Brand Voice Enforcer", isolation: "in-process", capability: "enforce-brand-voice", director: "creative-director", input: "ContentDraft", output: "VoiceValidatedContent", role: "Reviews all copy against extracted brand voice guidelines. Rewrites passages that deviate from tone, vocabulary, or personality.", artifactDesc: "Revised content with voice deviation report and correction rationale", validators: "brand-voice-extraction, anti-slop-gate" },
  { domain: "content", name: "testimonial-author", title: "Testimonial Author", isolation: "in-process", capability: "author-testimonials", director: "creative-director", input: "TestimonialSpec", output: "TestimonialSet", role: "Authors realistic testimonial copy with persona diversity and conversion-optimized framing. Flags synthetic content for disclosure.", artifactDesc: "Testimonial set with persona metadata and AI disclosure flags", validators: "anti-slop-gate, ai-disclosure" },
  { domain: "content", name: "pricing-author", title: "Pricing Author", isolation: "in-process", capability: "author-pricing", director: "creative-director", input: "PricingSpec", output: "PricingContent", role: "Authors pricing tier copy, feature bullets, and CTA text optimized for conversion. Applies cognitive load gate.", artifactDesc: "Pricing section content with tier structure, feature bullets, and CTA variants", validators: "conversion-gate, cognitive-load-gate" },
  { domain: "content", name: "faq-author", title: "FAQ Author", isolation: "in-process", capability: "author-faq", director: "creative-director", input: "FAQSpec", output: "FAQContent", role: "Authors FAQ content with structured data markup. Targets featured snippet eligibility and GEO citation patterns.", artifactDesc: "FAQ content with JSON-LD structured data and SEO optimization notes", validators: "structured-data-v2, geo-optimization" },

  // ── Mobile (5) ─────────────────────────────────────────────────────────────
  { domain: "mobile", name: "swift-author", title: "Swift/SwiftUI Author", isolation: "worktree", capability: "author-swift", director: "mobile-director", input: "MobileSpec", output: "SwiftArtifact", role: "Builds SwiftUI views with DNA token mapping to SwiftUI design tokens, SF Symbols, NavigationStack, and HIG compliance.", artifactDesc: "Swift source files with DNA token bindings, NavigationStack config, and HIG checklist", validators: "mobile-swift, mobile-quality-gate" },
  { domain: "mobile", name: "kotlin-author", title: "Kotlin/Compose Author", isolation: "worktree", capability: "author-kotlin", director: "mobile-director", input: "MobileSpec", output: "KotlinArtifact", role: "Builds Jetpack Compose UIs with Material You DNA bridge, adaptive layouts for foldables, and ViewModel architecture.", artifactDesc: "Kotlin source files with Compose components, Material You theme bindings, and ViewModel", validators: "mobile-kotlin, mobile-quality-gate" },
  { domain: "mobile", name: "rn-author", title: "React Native Author", isolation: "worktree", capability: "author-react-native", director: "mobile-director", input: "MobileSpec", output: "RNArtifact", role: "Builds React Native bare workflow components with NativeWind DNA bridge, React Navigation v7, and Reanimated 3.", artifactDesc: "React Native source files with NativeWind styles, navigation config, and animation setup", validators: "mobile-react-native, mobile-quality-gate" },
  { domain: "mobile", name: "expo-author", title: "Expo Author", isolation: "worktree", capability: "author-expo", director: "mobile-director", input: "MobileSpec", output: "ExpoArtifact", role: "Builds Expo managed workflow apps with EAS Build config, Expo Router, OTA updates, and config plugin setup.", artifactDesc: "Expo source files with app.config.js, Expo Router setup, and EAS build config", validators: "mobile-expo, mobile-quality-gate" },
  { domain: "mobile", name: "flutter-author", title: "Flutter Author", isolation: "worktree", capability: "author-flutter", director: "mobile-director", input: "MobileSpec", output: "FlutterArtifact", role: "Builds Flutter widgets with ThemeData DNA mapping, go_router navigation, Riverpod state, and platform adaptive widgets.", artifactDesc: "Dart source files with ThemeData bindings, go_router config, and Riverpod providers", validators: "mobile-flutter, mobile-quality-gate" },

  // ── Integration (8) ────────────────────────────────────────────────────────
  { domain: "integration", name: "supabase-integration-author", title: "Supabase Integration Author", isolation: "worktree", capability: "author-supabase-integration", director: "wave-director", input: "IntegrationSpec", output: "SupabaseIntegration", role: "Scaffolds Supabase integration: auth, Postgres schema, RLS policies, realtime subscriptions, and storage config.", artifactDesc: "Supabase integration files with schema migrations, RLS policies, and client setup", validators: "supabase-postgres, supabase-rls" },
  { domain: "integration", name: "stripe-integration-author", title: "Stripe Integration Author", isolation: "worktree", capability: "author-stripe-integration", director: "wave-director", input: "IntegrationSpec", output: "StripeIntegration", role: "Scaffolds Stripe payment integration: checkout session, subscription management, webhook handling, and payment element theming.", artifactDesc: "Stripe integration files with webhook handler, checkout config, and DNA-themed payment element", validators: "stripe-integration, security" },
  { domain: "integration", name: "hubspot-integration-author", title: "HubSpot Integration Author", isolation: "worktree", capability: "author-hubspot-integration", director: "wave-director", input: "IntegrationSpec", output: "HubSpotIntegration", role: "Scaffolds HubSpot CRM integration: forms, contact sync, marketing automation hooks, and CMS API.", artifactDesc: "HubSpot integration files with form embed, contact sync API, and CMS connection", validators: "hubspot-integration" },
  { domain: "integration", name: "shopify-integration-author", title: "Shopify Integration Author", isolation: "worktree", capability: "author-shopify-integration", director: "wave-director", input: "IntegrationSpec", output: "ShopifyIntegration", role: "Scaffolds Shopify Storefront API integration: product listings, cart, checkout, and DNA-themed product display.", artifactDesc: "Shopify integration files with Storefront API client, cart hooks, and checkout config", validators: "shopify-integration, ecommerce-ui" },
  { domain: "integration", name: "medusa-integration-author", title: "Medusa Integration Author", isolation: "worktree", capability: "author-medusa-integration", director: "wave-director", input: "IntegrationSpec", output: "MedusaIntegration", role: "Scaffolds Medusa v2 headless commerce integration with product catalog, cart, and checkout flows.", artifactDesc: "Medusa integration files with JS SDK client, product hooks, and cart management", validators: "commerce-medusa, ecommerce-ui" },
  { domain: "integration", name: "hydrogen-integration-author", title: "Hydrogen Integration Author", isolation: "worktree", capability: "author-hydrogen-integration", director: "wave-director", input: "IntegrationSpec", output: "HydrogenIntegration", role: "Scaffolds Shopify Hydrogen storefront with Oxygen deployment config, Remix routes, and DNA-bound storefront components.", artifactDesc: "Hydrogen integration files with Remix routes, Storefront API bindings, and Oxygen config", validators: "commerce-hydrogen, ecommerce-ui" },
  { domain: "integration", name: "propstack-integration-author", title: "Propstack Integration Author", isolation: "worktree", capability: "author-propstack-integration", director: "wave-director", input: "IntegrationSpec", output: "PropstackIntegration", role: "Scaffolds Propstack real estate CRM integration: property listings, search, and lead capture forms.", artifactDesc: "Propstack integration files with listings API client, search filters, and CRM sync", validators: "propstack-integration" },
  { domain: "integration", name: "woocommerce-integration-author", title: "WooCommerce Integration Author", isolation: "worktree", capability: "author-woocommerce-integration", director: "wave-director", input: "IntegrationSpec", output: "WooCommerceIntegration", role: "Scaffolds WooCommerce REST API integration: product grids, cart management, order flows, and DNA-themed checkout.", artifactDesc: "WooCommerce integration files with REST API client, cart hooks, and checkout components", validators: "woocommerce-integration, ecommerce-ui" },

  // ── Polish (5) ─────────────────────────────────────────────────────────────
  { domain: "polish", name: "polisher", title: "Polisher", isolation: "in-process", capability: "polish-section", director: "wave-director", input: "SectionArtifact", output: "PolishedArtifact", role: "Applies final polish pass: micro-interactions, hover states, focus rings, loading skeletons, and transition refinements.", artifactDesc: "Polished section files with micro-interaction layer and transition polish", validators: "polish-pass, interaction-fidelity-gate" },
  { domain: "polish", name: "visual-refiner", title: "Visual Refiner", isolation: "in-process", capability: "refine-visuals", director: "wave-director", input: "SectionArtifact", output: "RefinedArtifact", role: "Closed-loop visual refinement: captures Playwright screenshots, compares against reference targets, applies corrections until delta converges.", artifactDesc: "Refined section with before/after screenshots and convergence log", validators: "visual-qa-protocol, closed-loop-iteration" },
  { domain: "polish", name: "microcopy-polisher", title: "Microcopy Polisher", isolation: "in-process", capability: "polish-microcopy", director: "creative-director", input: "SectionArtifact", output: "PolishedCopy", role: "Final microcopy review and polish: tightens CTAs, removes filler words, enforces anti-slop gate, checks brand voice.", artifactDesc: "Polished copy with change log and anti-slop gate pass confirmation", validators: "anti-slop-gate, copy-intelligence" },
  { domain: "polish", name: "a11y-polisher", title: "Accessibility Polisher", isolation: "in-process", capability: "polish-a11y", director: "wave-director", input: "SectionArtifact", output: "A11yPolishedArtifact", role: "Applies accessibility polish: ARIA labels, focus management, color contrast corrections, and keyboard navigation.", artifactDesc: "A11y-polished section with axe-core pass confirmation and WCAG 2.1 AA checklist", validators: "accessibility, cognitive-accessibility" },
  { domain: "polish", name: "perf-polisher", title: "Performance Polisher", isolation: "in-process", capability: "polish-performance", director: "wave-director", input: "SectionArtifact", output: "PerfPolishedArtifact", role: "Applies performance polish: image optimization, lazy loading, bundle splitting, and CWV budget validation.", artifactDesc: "Perf-polished section with Lighthouse score delta and budget compliance report", validators: "performance-patterns, perf-budgets" },

  // ── Critics (8) ────────────────────────────────────────────────────────────
  { domain: "critics", name: "typography-critic", title: "Typography Critic", isolation: "in-process", capability: "critique-typography", director: "quality-director", input: "SectionArtifact", output: "TypographyCritique", role: "Evaluates typography against quality gate axis: scale discipline, hierarchy clarity, archetype font personality, and readability.", artifactDesc: "Typography critique with score, flagged violations, and fix suggestions", validators: "typography-rules, quality-gate-v3" },
  { domain: "critics", name: "color-critic", title: "Color Critic", isolation: "in-process", capability: "critique-color", director: "quality-director", input: "SectionArtifact", output: "ColorCritique", role: "Evaluates color system against DNA tokens, contrast ratios, and archetype color rules. Checks for token drift.", artifactDesc: "Color critique with ΔE2000 drift scores, contrast failures, and token correction list", validators: "design-dna, quality-gate-v3" },
  { domain: "critics", name: "motion-critic", title: "Motion Critic", isolation: "in-process", capability: "critique-motion", director: "quality-director", input: "SectionArtifact", output: "MotionCritique", role: "Evaluates motion design against quality gate: intentionality, DNA motion token usage, reduced-motion compliance.", artifactDesc: "Motion critique with easing analysis, token violations, and performance impact", validators: "motion-health, quality-gate-v3" },
  { domain: "critics", name: "narrative-critic", title: "Narrative Critic", isolation: "in-process", capability: "critique-narrative", director: "quality-director", input: "SectionSequence", output: "NarrativeCritique", role: "Evaluates cross-section story arc coherence, beat sequencing validity, and emotional progression.", artifactDesc: "Narrative critique with arc score, beat transition analysis, and coherence gaps", validators: "emotional-arc, quality-gate-v3" },
  { domain: "critics", name: "conversion-critic", title: "Conversion Critic", isolation: "in-process", capability: "critique-conversion", director: "quality-director", input: "SectionArtifact", output: "ConversionCritique", role: "Evaluates conversion readiness: CTA clarity, social proof placement, friction reduction, and conversion gate compliance.", artifactDesc: "Conversion critique with CTA scores, funnel analysis, and optimization suggestions", validators: "conversion-gate, conversion-patterns" },
  { domain: "critics", name: "awwwards-judge-simulator", title: "Awwwards Judge Simulator", isolation: "in-process", capability: "simulate-awwwards", director: "quality-director", input: "FullPageArtifact", output: "AwwwardsScore", role: "Simulates Awwwards SOTD judge scoring across 4 axes: Design, Usability, Creativity, Content. Targets 8.0+ average.", artifactDesc: "Awwwards score report with per-axis scores, SOTD gap analysis, and win criteria", validators: "awwwards-scoring, quality-gate-v3" },
  { domain: "critics", name: "first-time-visitor-critic", title: "First-Time Visitor Critic", isolation: "in-process", capability: "critique-first-visit", director: "quality-director", input: "FullPageArtifact", output: "FirstVisitCritique", role: "Simulates first-time visitor experience: 5-second test, clarity of value proposition, and confusion points.", artifactDesc: "First-visit critique with clarity score, confusion map, and above-fold effectiveness", validators: "ux-heuristics-gate, synthetic-user-testing" },
  { domain: "critics", name: "skeptic-persona-critic", title: "Skeptic Persona Critic", isolation: "in-process", capability: "critique-skeptic", director: "quality-director", input: "FullPageArtifact", output: "SkepticCritique", role: "Applies skeptical buyer persona: challenges trust signals, probes objection handling, and tests social proof credibility.", artifactDesc: "Skeptic critique with trust score, objection inventory, and credibility gap list", validators: "conversion-gate, ux-intelligence" },

  // ── Research (6) ───────────────────────────────────────────────────────────
  { domain: "research", name: "sotd-scout", title: "SOTD Scout", isolation: "in-process", capability: "scout-sotd", director: "research-director", input: "ResearchSpec", output: "SOTDReport", role: "Scouts recent Awwwards SOTD winners in the target vertical. Extracts design patterns, score benchmarks, and differentiators.", artifactDesc: "SOTD report with winner list, pattern analysis, score benchmarks, and gap targets", validators: "competitive-benchmarking, reference-benchmarking" },
  { domain: "research", name: "competitor-analyzer", title: "Competitor Analyzer", isolation: "in-process", capability: "analyze-competitors", director: "research-director", input: "CompetitorList", output: "CompetitorReport", role: "Analyzes competitor sites for design quality, UX patterns, conversion strategies, and differentiation opportunities.", artifactDesc: "Competitor report with quality scores, pattern inventory, and white-space opportunities", validators: "competitive-benchmarking" },
  { domain: "research", name: "archetype-researcher", title: "Archetype Researcher", isolation: "in-process", capability: "research-archetype", director: "research-director", input: "ArchetypeSpec", output: "ArchetypeResearch", role: "Researches archetype-specific visual references, color systems, typography precedents, and motion language.", artifactDesc: "Archetype research doc with reference images, color analysis, and technique inventory", validators: "design-archetypes, design-brainstorm" },
  { domain: "research", name: "trend-scout", title: "Trend Scout", isolation: "in-process", capability: "scout-trends", director: "research-director", input: "TrendSpec", output: "TrendReport", role: "Identifies emerging design and UX trends relevant to the project vertical. Flags trends conflicting with archetype.", artifactDesc: "Trend report with signals, relevance scores, and archetype compatibility assessment", validators: "design-archetypes" },
  { domain: "research", name: "reference-library-curator", title: "Reference Library Curator", isolation: "in-process", capability: "curate-references", director: "research-director", input: "ResearchReport", output: "ReferenceLibrary", role: "Curates and indexes reference sites and assets into the project reference library. Manages semantic search index.", artifactDesc: "Reference library entries with semantic tags, beat type assignments, and quality scores", validators: "reference-library-rag" },
  { domain: "research", name: "pattern-miner", title: "Pattern Miner", isolation: "in-process", capability: "mine-patterns", director: "research-director", input: "ReferenceLibrary", output: "PatternCatalog", role: "Extracts reusable design patterns from reference sites. Identifies cross-archetype techniques and innovation opportunities.", artifactDesc: "Pattern catalog with technique descriptions, usage contexts, and implementation hints", validators: "reference-benchmarking, cross-pollination" },

  // ── Observability (6) ──────────────────────────────────────────────────────
  { domain: "observability", name: "lighthouse-runner", title: "Lighthouse Runner", isolation: "in-process", capability: "run-lighthouse", director: "quality-director", input: "DeployURL", output: "LighthouseReport", role: "Runs Lighthouse CI against preview deployments. Enforces perf budget thresholds and flags CWV regressions.", artifactDesc: "Lighthouse report with per-metric scores, CWV values, and budget delta", validators: "lighthouse-ci-setup, perf-budgets" },
  { domain: "observability", name: "axe-runner", title: "Axe Runner", isolation: "in-process", capability: "run-axe", director: "quality-director", input: "DeployURL", output: "AxeReport", role: "Runs axe-core accessibility audit against deployed preview. Reports WCAG 2.1 AA violations with fix guidance.", artifactDesc: "Axe report with violation list, severity levels, and remediation code snippets", validators: "accessibility, a11y-test-gen" },
  { domain: "observability", name: "bundle-analyzer", title: "Bundle Analyzer", isolation: "in-process", capability: "analyze-bundle", director: "quality-director", input: "BuildArtifact", output: "BundleReport", role: "Analyzes production bundle composition. Flags oversized chunks, duplicate dependencies, and tree-shaking failures.", artifactDesc: "Bundle report with size breakdown, dependency tree, and optimization opportunities", validators: "performance-patterns, perf-budgets" },
  { domain: "observability", name: "vr-snapshot-taker", title: "Visual Regression Snapshot Taker", isolation: "in-process", capability: "take-vr-snapshots", director: "quality-director", input: "DeployURL", output: "SnapshotSet", role: "Captures 4-breakpoint visual regression snapshots via Playwright. Diffs against baseline and flags regressions.", artifactDesc: "Snapshot set with baseline diffs, regression flags, and diff percentage per breakpoint", validators: "visual-regression, visual-qa-protocol" },
  { domain: "observability", name: "synthetic-persona-prober", title: "Synthetic Persona Prober", isolation: "in-process", capability: "probe-synthetic-persona", director: "quality-director", input: "PersonaSpec", output: "PersonaProbeReport", role: "Runs synthetic user personas through the full page journey. Validates task completion, confusion points, and conversion path.", artifactDesc: "Persona probe report with journey completion rates, confusion map, and CRO flags", validators: "synthetic-user-testing, ux-heuristics-gate" },
  { domain: "observability", name: "telemetry-ingester", title: "Telemetry Ingester", isolation: "in-process", capability: "ingest-telemetry", director: "quality-director", input: "TelemetryStream", output: "TelemetryReport", role: "Ingests RUM and synthetic telemetry. Tracks CWV trends, error rates, and user flow drop-offs against SLO budgets.", artifactDesc: "Telemetry report with CWV trends, error rates, SLO status, and alert thresholds", validators: "slo-error-budgets, opentelemetry-traces" },

  // ── CMS (3) ────────────────────────────────────────────────────────────────
  { domain: "cms", name: "sanity-author", title: "Sanity Author", isolation: "worktree", capability: "author-sanity", director: "wave-director", input: "CMSSpec", output: "SanitySchema", role: "Authors Sanity schema definitions, GROQ queries, and DNA-themed Studio components for content management.", artifactDesc: "Sanity schema files with document types, GROQ queries, and Studio customization", validators: "cms-sanity, cms-content-pipeline" },
  { domain: "cms", name: "contentful-author", title: "Contentful Author", isolation: "worktree", capability: "author-contentful", director: "wave-director", input: "CMSSpec", output: "ContentfulSchema", role: "Authors Contentful content model definitions and GraphQL query fragments with DNA token field mappings.", artifactDesc: "Contentful migration scripts, content type definitions, and GraphQL fragments", validators: "cms-reconnect, cms-content-pipeline" },
  { domain: "cms", name: "payload-author", title: "Payload Author", isolation: "worktree", capability: "author-payload", director: "wave-director", input: "CMSSpec", output: "PayloadSchema", role: "Authors Payload CMS collection and global definitions with DNA-themed admin UI and access control policies.", artifactDesc: "Payload collection config files with field definitions, hooks, and admin customization", validators: "cms-payload, cms-content-pipeline" },

  // ── DB/API (3) ─────────────────────────────────────────────────────────────
  { domain: "db-api", name: "prisma-schema-author", title: "Prisma Schema Author", isolation: "worktree", capability: "author-prisma-schema", director: "wave-director", input: "DataSpec", output: "PrismaSchema", role: "Authors Prisma schema from content and data requirements. Generates migrations and type-safe client bindings.", artifactDesc: "schema.prisma with model definitions, relations, and migration files", validators: "db-schema-from-content" },
  { domain: "db-api", name: "api-route-author", title: "API Route Author", isolation: "worktree", capability: "author-api-routes", director: "wave-director", input: "APISpec", output: "APIRoutes", role: "Authors framework-native API routes with Zod validation, error handling, and OpenAPI documentation.", artifactDesc: "API route files with Zod schemas, error taxonomy, and OpenAPI annotations", validators: "api-patterns, api-routes" },
  { domain: "db-api", name: "edge-function-author", title: "Edge Function Author", isolation: "worktree", capability: "author-edge-function", director: "wave-director", input: "EdgeSpec", output: "EdgeFunction", role: "Authors Vercel Edge Functions with streaming responses, geolocation logic, and bot detection integration.", artifactDesc: "Edge function files with runtime config, geo routing, and streaming setup", validators: "vercel-sandbox, rsc-patterns" },

  // ── Testing (3) ────────────────────────────────────────────────────────────
  { domain: "testing", name: "playwright-test-author", title: "Playwright Test Author", isolation: "worktree", capability: "author-playwright-tests", director: "wave-director", input: "TestSpec", output: "PlaywrightTests", role: "Authors Playwright E2E tests for critical user journeys, visual regression baselines, and accessibility checks.", artifactDesc: "Playwright test files with page objects, visual snapshots, and accessibility assertions", validators: "e2e-test-gen, visual-regression-gen" },
  { domain: "testing", name: "vitest-author", title: "Vitest Author", isolation: "worktree", capability: "author-vitest", director: "wave-director", input: "TestSpec", output: "VitestTests", role: "Authors Vitest unit and integration tests for utilities, hooks, and component logic with coverage targets.", artifactDesc: "Vitest test files with coverage configuration and mock setup", validators: "testing-patterns, api-test-scaffolds" },
  { domain: "testing", name: "storybook-story-author", title: "Storybook Story Author", isolation: "worktree", capability: "author-storybook-stories", director: "wave-director", input: "ComponentSpec", output: "StorybookStories", role: "Authors Storybook stories for all shared components with controls, docs, and accessibility addon integration.", artifactDesc: "Story files with controls metadata, docs blocks, and a11y addon config", validators: "testing-patterns, design-system-scaffold" },

  // ── Deployment (3) ─────────────────────────────────────────────────────────
  { domain: "deployment", name: "vercel-config-author", title: "Vercel Config Author", isolation: "worktree", capability: "author-vercel-config", director: "wave-director", input: "DeploySpec", output: "VercelConfig", role: "Authors vercel.json with routing rules, edge config, caching strategies, and environment variable schema.", artifactDesc: "vercel.json with routing config, edge config, and deployment settings", validators: "deploy-preview, env-var-scheme" },
  { domain: "deployment", name: "ci-pipeline-author", title: "CI Pipeline Author", isolation: "worktree", capability: "author-ci-pipeline", director: "wave-director", input: "CISpec", output: "CIPipeline", role: "Authors GitHub Actions or CI pipeline with Lighthouse CI, Playwright preview smoke, and quality gate checks.", artifactDesc: "CI pipeline YAML with quality gate jobs, Lighthouse CI config, and deployment hooks", validators: "lighthouse-ci-setup, git-workflow" },
  { domain: "deployment", name: "docker-author", title: "Docker Author", isolation: "worktree", capability: "author-docker", director: "wave-director", input: "DeploySpec", output: "DockerConfig", role: "Authors Dockerfile and docker-compose.yml for self-hosted deployment with standalone Next.js output.", artifactDesc: "Dockerfile, docker-compose.yml, and .dockerignore with multi-stage build config", validators: "performance-patterns" },

  // ── AI-feature (3) ─────────────────────────────────────────────────────────
  { domain: "ai-feature", name: "chat-ui-author", title: "Chat UI Author", isolation: "worktree", capability: "author-chat-ui", director: "wave-director", input: "ChatUISpec", output: "ChatUIComponent", role: "Builds AI chat UI components with Vercel AI SDK v4, streaming responses, and DNA-themed message bubbles.", artifactDesc: "Chat UI component files with AI SDK hooks, streaming config, and DNA token bindings", validators: "ai-ui-components, agentic-ux-patterns" },
  { domain: "ai-feature", name: "rag-pipeline-author", title: "RAG Pipeline Author", isolation: "worktree", capability: "author-rag-pipeline", director: "wave-director", input: "RAGSpec", output: "RAGPipeline", role: "Scaffolds RAG pipeline with Supabase pgvector, embedding generation, and retrieval-augmented generation routes.", artifactDesc: "RAG pipeline files with vector store config, embedding routes, and retrieval logic", validators: "supabase-vector, ai-pipeline-features" },
  { domain: "ai-feature", name: "agent-trace-ui-author", title: "Agent Trace UI Author", isolation: "worktree", capability: "author-agent-trace-ui", director: "wave-director", input: "AgentTraceSpec", output: "AgentTraceUIComponent", role: "Builds agent trace visualization UI with AG-UI event stream rendering and step-by-step thought display.", artifactDesc: "Agent trace UI component with AG-UI event bindings and thought visualization", validators: "agent-trace-ui, agentic-ux-patterns" },

  // ── Ingestion (4) ──────────────────────────────────────────────────────────
  { domain: "ingestion", name: "sitemap-crawler", title: "Sitemap Crawler", isolation: "in-process", capability: "crawl-sitemap", director: "research-director", input: "CrawlSpec", output: "CrawlManifest", role: "Recursive BFS sitemap crawl with per-sitemap error events. Captures HTML, computed styles, and 4-breakpoint screenshots.", artifactDesc: "Crawl manifest with URL inventory, page metadata, asset list, and error events", validators: "url-scrape-ingestion, preservation-ledger" },
  { domain: "ingestion", name: "dna-reverse-engineer", title: "DNA Reverse Engineer", isolation: "in-process", capability: "reverse-engineer-dna", director: "research-director", input: "CrawlManifest", output: "ExtractedDNA", role: "Extracts Design DNA from captured CSS variables and computed styles. Runs pixel-kmeans with ΔE2000 perceptual distance.", artifactDesc: "Extracted DNA document with color tokens, font stack, spacing scale, and confidence scores", validators: "dna-reverse-engineer, pixel-dna-extraction" },
  { domain: "ingestion", name: "interaction-replay-fitter", title: "Interaction Replay Fitter", isolation: "in-process", capability: "fit-interaction-replay", director: "research-director", input: "PlaywrightTrace", output: "MotionInventory", role: "Fits Playwright traces to 7 cubic-Bezier easing presets and generates MOTION-INVENTORY.md with exact preset matches.", artifactDesc: "MOTION-INVENTORY.md with easing fits, confidence scores, and replay recommendations", validators: "interaction-replay, motion-health" },
  { domain: "ingestion", name: "cms-schema-introspector", title: "CMS Schema Introspector", isolation: "in-process", capability: "introspect-cms-schema", director: "research-director", input: "CMSConnectionSpec", output: "CMSSchemaReport", role: "Introspects CMS schemas via GROQ (Sanity), CMA (Contentful), or OpenAPI (Payload). Maps content types to DNA sections.", artifactDesc: "CMS schema report with content type inventory, field mappings, and DNA section assignments", validators: "cms-sanity, cms-reconnect, cms-payload" },

  // ── Misc (5) ───────────────────────────────────────────────────────────────
  { domain: "misc", name: "sitemap-author", title: "Sitemap Author", isolation: "worktree", capability: "author-sitemap", director: "wave-director", input: "SiteSpec", output: "SitemapXML", role: "Authors XML sitemaps (standard, image, video, news) with changefreq, priority, and hreflang entries.", artifactDesc: "sitemap.xml files with full entry set and robots.txt integration", validators: "seo-technical" },
  { domain: "misc", name: "og-image-author", title: "OG Image Author", isolation: "worktree", capability: "author-og-images", director: "wave-director", input: "OGSpec", output: "OGImageRoutes", role: "Authors dynamic OG image generation routes with next/og, DNA typography, and brand color templates.", artifactDesc: "OG image route files with next/og templates and DNA token bindings", validators: "og-images, seo-meta" },
  { domain: "misc", name: "legal-doc-author", title: "Legal Doc Author", isolation: "worktree", capability: "author-legal-docs", director: "wave-director", input: "LegalSpec", output: "LegalDocs", role: "Authors privacy policy, terms of service, and cookie consent documents with jurisdiction-specific clauses.", artifactDesc: "Legal document files with jurisdiction flags, cookie consent config, and policy pages", validators: "privacy-policy-generator, cookie-compliance" },
  { domain: "misc", name: "email-template-author", title: "Email Template Author", isolation: "worktree", capability: "author-email-templates", director: "wave-director", input: "EmailSpec", output: "EmailTemplates", role: "Authors React Email or MJML transactional email templates with DNA-aligned styling and dark mode support.", artifactDesc: "Email template files with responsive layout, DNA colors, and Resend/Postmark config", validators: "email-templates" },
  { domain: "misc", name: "n8n-workflow-author", title: "n8n Workflow Author", isolation: "worktree", capability: "author-n8n-workflow", director: "wave-director", input: "WorkflowSpec", output: "N8NWorkflow", role: "Authors n8n automation workflow JSON for lead capture, CRM sync, and notification pipelines.", artifactDesc: "n8n workflow JSON with node config, credential placeholders, and activation steps", validators: "n8n-workflows" }
];

function buildWorkerMd(w) {
  return `---
name: ${w.name}
id: genorah/${w.name}
version: 4.0.0
channel: stable
tier: worker
description: ${w.description}
capabilities:
  - id: ${w.capability}
    input: ${w.input}
    output: ${w.output}
tools:
  - Read
  - Write
  - Edit
  - Bash
  - Grep
  - Glob
isolation: ${w.isolation}
director: ${w.director}
domain: ${w.domain}
---

# ${w.title}

## Role

${w.role}

## Input Contract

${w.input}: task envelope received from ${w.director}

## Output Contract

Returns \`Result<T>\` envelope per \`@genorah/protocol\`:
- \`artifact\`: ${w.artifactDesc}
- \`verdicts\`: validation results from ${w.validators}
- \`followups\`: []

## Protocol

1. Receive task envelope from ${w.director}
2. Execute domain-specific implementation
3. Run validators: ${w.validators}
4. Return Result envelope

## Skills Invoked

_Stubs — fleshed out in M2-M5_

## Followups

_None by default — director-initiated only_
`;
}

let count = 0;
for (const w of workers) {
  const filePath = join(outDir, `${w.name}.md`);
  writeFileSync(filePath, buildWorkerMd(w));
  count++;
}

console.log(`Done. Created ${count} worker agent files in agents/workers/`);
if (count !== 95) {
  console.error(`ERROR: Expected 95 workers, got ${count}`);
  process.exit(1);
}
